In [ ]:
#Eugene Fotsing
#CTEC298 
#Jupiter Notebook
#Numpy Tutorial

In [31]:
import numpy as np

#creating a table
A = np.array([[1,2,3],[4,5,6],[7,8,9]])

A


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
#Accessing each row
A[0]

array([1, 2, 3])

In [5]:
A[1]

array([4, 5, 6])

In [7]:
A[2]

array([7, 8, 9])

In [15]:
#Accessing each column
A[:,0]

array([1, 4, 7])

In [11]:
A[:,1]

array([2, 5, 8])

In [13]:
A[:,2]

array([3, 6, 9])

In [21]:
#Accessing cell
A[1,0]

4

In [23]:
A[2,2]

9

In [25]:
# Ask what the shape of a array
A.shape

(3, 3)

In [27]:
np.shape(A)

(3, 3)

In [33]:
#Accessing a specific section of the table "[4,5]"
A[1:2,0:2]

array([[4, 5]])

In [35]:
A[1:2,:2]

array([[4, 5]])

In [37]:
A[1:3,1:3]

array([[5, 6],
       [8, 9]])

In [39]:
A[1:,1:]

array([[5, 6],
       [8, 9]])

In [41]:
#Applying Mask/filter to an array

A>5

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [43]:
#Accessing only the eleemnts of the array base of a mask/filter
A[A>5]

array([6, 7, 8, 9])

In [45]:
#Create a array of zero base of the number of colums and rows
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [49]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [51]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [53]:
np.empty((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [55]:
#Create an array with random number on it
np.random.random((4,4))

array([[0.33780761, 0.69415065, 0.80889941, 0.8819975 ],
       [0.26290492, 0.66844683, 0.41211809, 0.52813386],
       [0.68109375, 0.92660023, 0.88190866, 0.99810523],
       [0.73305986, 0.50749398, 0.72387508, 0.63744394]])

In [65]:
#Stacking horizontally two table

B = np.zeros((3,3))
np.hstack((A,B))

array([[1., 2., 3., 0., 0., 0.],
       [4., 5., 6., 0., 0., 0.],
       [7., 8., 9., 0., 0., 0.]])

In [67]:
#stacking vertically two table/array
np.vstack((A,B))

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [69]:
#spliting array 

np.hsplit(A,3)


[array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]]),
 array([[3],
        [6],
        [9]])]

In [71]:
np.vsplit(B,3)

[array([[0., 0., 0.]]), array([[0., 0., 0.]]), array([[0., 0., 0.]])]

In [73]:
#Linear operation
np.transpose(A)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [77]:
A.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [79]:
#multiply two array
np.dot(A,A)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [81]:
A@A

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [83]:
A@B

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [85]:
A/2

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ],
       [3.5, 4. , 4.5]])

In [91]:
#accessing the mean of the whole Array
np.mean(A)

5.0

In [89]:
#Accessing the mean for every single colomn
np.mean(A,axis=0)

array([4., 5., 6.])

In [93]:
#Accessing the standard deviation of the array

np.std(A)

2.581988897471611

In [95]:
#Accessing the standard deviation of the column

np.std(A,axis=0)

array([2.44948974, 2.44948974, 2.44948974])